language: node_js
sudo: false
node_js:
- 6.6.0
deploy:
  provider: heroku
  api_key:
    secure: 2zrh1gyMRSHm3YVdyXRiIikL0OwLdxFjy4u8XCQGo2mwsPybjx6fGsBlD0tSb3CFILcXzZ3mr75IJVqZWhXwwtYMsgwcm+ai4RQkdf1MKDB5Jd0H+GOJQY3dzbW0joFwRwwpkW4Z0jMTZsC/ZoR0JUlfq7tbuNEr9N5pRNm0rDowjCmi4IoqgSG6kD4BywcIJsj06cU1D1gPOML4656vWl2Lmhy5sTyD9MmMT1kUS/DOdwsUzJEPPfVA0PfWhHyLSaKihadoiM/xFqET6uJOCcY6NX6VbAfPGYlFQcQP08C/FWlx8sntLxT2xzPwcLJadnKVVik7Q6z3hVSd/5H+KOYQ20HiTf232nVWXJ277+8LF7yj4zWz5o6IrPortLH2lSDESw5Y+xjhmQcxBbu7tVXMWgaNc8dGTBu4wwWGfhGDQXihJUI6Sy3/SvHIv1ZKB3k9saMoaCKpgKV24+RMhpFgx49iUntzENAJffstNb2sSFcqFksIyFzxl3txiGm0Juu1AqRiYlvJnd2OPkY53aFf26E77YMjtY2M5HSsKYtjg2Oj72aKMVCeuYgTC2FurHeiOiCit29dGXsKX3zv4pPx+FnsjYH51zIDFUr1MTLkAp9y2vx2ExZ3sxuoTmoF0+93twEjqqJCVGMAO8IAdQOFOW8TTbg0f4Uet5kCfJM=
  app:
    master: safe-taiga-54899
    production: still-fjord-35466
  run:
    - npm run migrate
  on:
    repo: GuildCrafts/floworky
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- TRAVIS=travis CXX=g++-4.8
notifications:
  slack:
    secure: LYExzyFL+OHpjhalnMg8m5dTDH/Dh3H7nlSOMJYopfn9hyWLLkNEtdIXoR3YcxIuknAnFwHUPrTZAGeNup9V2+1DN2Mbv5PpOLpjR+xB/DtcrKuOIxLx59EV+UifHmrF1JuatH2sN0Z2Yjzhu34ll4kJJL7jha1hwAYDfsJNw/wa/O3PynL0/uSc+niy3CP+QBxFILHJ7vEm9qWgPxoa9u6wL5I3Bb5I5UjKA6sRkY/yf0xkW4ifhV0sqgR9SX6Sitd/WNYlAZ5EnaOiyKOVYnEmKPMmilKjJkOhYwTRnWjHx6kc/yzTPVZy294sCFFCP+U9Ukznoxs1o/4FXKC+a4xkRJun1uJY54G09Ga4wlDx9cqi8u52VN6kWOQ8MHEkj3q8GQl5okyOS+QSln1OBZqFRTHTn3YCBHgTuu6TsB5kfELCTk5ty5EOITe5pED+flyiyq6jAbZQ56C37jLmC68GBWQLb+l2CHvcIr9DmCftK/H4t9qBQfF3Vi3Fv5RNGD5v0jsfZAZ71WLQoRxC8jTIgb3cagKstDEbiPQCOcpBBKJJ2zH55O35o2vuqSekUPll+Te915b5rDzE2qIXrdZMH041/B+qU2SGmEuhgHxU41IaCtJxIB6a8VA48mpp5Wtee5LytrdtpOiZty+0FrusmBC8sqUbwcLPZCpKpIw=
